uint8      classId

float32    pf1x               # front point1 x
float32    pf1y               # front point1 y

float32    pf2x               # front point2 x
float32    pf2y               # front point2 y

float32    pf3x               # front point3 x
float32    pf3y               # front point3 y

float32    pf4x               # front point4 x
float32    pf4y               # front point4 y


float32    pr1x               # rear point1 x
float32    pr1y               # rear point1 y

float32    pr2x               # rear point2 x
float32    pr2y               # rear point2 y

float32    pr3x               # rear point3 x
float32    pr3y               # rear point3 y

float32    pr4x               # rear point4 x
float32    pr4y               # rear point4 y

float32    frontDepth         # front depth
float32    rearDepth          # rear depth

float32    topLeftGridX       # X pos of top-left grid in mm
float32    topLeftGridY       # Y pos of top-left grid in mm

float32    bottomRightGridX   # X pos of top-left grid in mm
float32    bottomRightGridY   # Y pos of top-left grid in mm

